version: 2.1
jobs:
  build-docker-image:
    docker:
      - image: docker:20.10.16-git
    steps:
      - checkout
      - run:
          name: "Build docker image"
          command: |
            docker build -t ${DOCKER_IMAGE} nginx/
  push-docker-image:
    docker:
      - image: docker:20.10.16-git
    steps:
      - checkout
      - run:
          name: "Login to docker hub"
          command: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - run:
          name: "Push docker image"
          command: |
            docker push ${DOCKER_IMAGE}
workflows:
  default:
    jobs:
      - build-docker-image:
          filters:
            branches:
              only: [main]
      - push-docker-image:
          requires:
            - build-docker-image