apiVersion: v1
kind: Pod
metadata:
  labels:
    app: udacity
  name: udacity-nginx
spec:
  containers:
    - name: udacity-nginx
      image: 18120211/udacity-nginx:test
      ports:
        - containerPort: 80

