apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udacity-cluster
  region: us-east-1

vpc:
  subnets:
    public:
      us-east-1d: { id: subnet-087281ff1ee83742a }
      us-east-1c: { id: subnet-0d8f26465562e408a }
      us-east-1b: { id: subnet-0f85137165f6256d0 }
      us-east-1a: { id: subnet-04e64dc3c677c7431 }

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      publicKeyName: udacity